services:
  wordpress:
    image: wordpress:7.0-php8.2-apache
    container_name: wordpress
    restart: always
    environment:
      WORDPRESSDBHOST: db
      WORDPRESSDBUSER: ${WP_USERNAME}
      WORDPRESSDBPASSWORD: ${WP_DATABASE_PASSWORD}
      WORDPRESSDBNAME: ${WP_DATABASE_NAME}
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - /opt/wp-comfy/wordpress:/var/www/html

  db:
    image: mariadb:10.6
    container_name: wordpress-db
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USERNAME: ${DB_USERNAME}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /opt/wp-comfy/db-data:/var/lib/mysql
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "0.0.0.0:6379:6379"

  python-orchestrator:
    build:
      context: /opt/wp-comfy/orchestrator
      dockerfile: Dockerfile
    container_name: python-orchestrator
    restart: always
    environment:
      WORDPRESS_URL: http://wordpress
      WORDPRESS_USER: ${WP_USERNAME}
      WORDPRESSAPPPASSWORD: ${WP_APP_PASSWORD}
      REDIS_URL: redis://redis:6379/0
      COMFYUI_URL: http://127.0.0.1:8188
    depends_on:
      - wordpress
      - redis
#      - comfyui
    ports:
      - "0.0.0.0:8000:8000"  # FastAPI/Flask

  celery-worker:
    build:
      context: /opt/wp-comfy/orchestrator
      dockerfile: Dockerfile
    container_name: celery-worker
    restart: always
    environment:
      WORDPRESS_URL: http://wordpress:80
      WORDPRESS_USER: ${WP_USERNAME}
      WORDPRESSAPPPASSWORD: ${WP_APP_PASSWORD}
      REDIS_URL: redis://redis:6379/0
      COMFYUI_URL: http://127.0.0.1:8188
    depends_on:
      - redis
#      - comfyui
    command: >
      celery -A tasks.celery_app worker
